server:
  port: 8999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8769/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
#  instance:
#    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - path=/contact/**


#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#          predicates:
#            - name: Path
#              args:
#                pattern: "'/api/' + serviceId + '/**'"
#        instances: 1
#        route-id-prefix: compositeRoute
#    discovery:
#      locator:
#        enabled: true
#        lower-case-service-id: true

#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - path=/user/**
#        - id: contact-service
#          uri: lb://contact-service
#          predicates:
#            - path=/contact/**


